# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/js/Documents/TJE2020_2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/js/Documents/TJE2020_2D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/js/Documents/TJE2020_2D/CMakeFiles /home/js/Documents/TJE2020_2D/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/js/Documents/TJE2020_2D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TJE

# Build rule for target.
TJE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TJE
.PHONY : TJE

# fast build rule for target.
TJE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/build
.PHONY : TJE/fast

#=============================================================================
# Target rules for targets named tweeny-dummy

# Build rule for target.
tweeny-dummy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tweeny-dummy
.PHONY : tweeny-dummy

# fast build rule for target.
tweeny-dummy/fast:
	$(MAKE) $(MAKESILENT) -f tweeny/CMakeFiles/tweeny-dummy.dir/build.make tweeny/CMakeFiles/tweeny-dummy.dir/build
.PHONY : tweeny-dummy/fast

src/Managers/ImageManager.o: src/Managers/ImageManager.cpp.o

.PHONY : src/Managers/ImageManager.o

# target to build an object file
src/Managers/ImageManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Managers/ImageManager.cpp.o
.PHONY : src/Managers/ImageManager.cpp.o

src/Managers/ImageManager.i: src/Managers/ImageManager.cpp.i

.PHONY : src/Managers/ImageManager.i

# target to preprocess a source file
src/Managers/ImageManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Managers/ImageManager.cpp.i
.PHONY : src/Managers/ImageManager.cpp.i

src/Managers/ImageManager.s: src/Managers/ImageManager.cpp.s

.PHONY : src/Managers/ImageManager.s

# target to generate assembly for a file
src/Managers/ImageManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Managers/ImageManager.cpp.s
.PHONY : src/Managers/ImageManager.cpp.s

src/Scenes/MenuScene.o: src/Scenes/MenuScene.cpp.o

.PHONY : src/Scenes/MenuScene.o

# target to build an object file
src/Scenes/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/MenuScene.cpp.o
.PHONY : src/Scenes/MenuScene.cpp.o

src/Scenes/MenuScene.i: src/Scenes/MenuScene.cpp.i

.PHONY : src/Scenes/MenuScene.i

# target to preprocess a source file
src/Scenes/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/MenuScene.cpp.i
.PHONY : src/Scenes/MenuScene.cpp.i

src/Scenes/MenuScene.s: src/Scenes/MenuScene.cpp.s

.PHONY : src/Scenes/MenuScene.s

# target to generate assembly for a file
src/Scenes/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/MenuScene.cpp.s
.PHONY : src/Scenes/MenuScene.cpp.s

src/Scenes/TestScene.o: src/Scenes/TestScene.cpp.o

.PHONY : src/Scenes/TestScene.o

# target to build an object file
src/Scenes/TestScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/TestScene.cpp.o
.PHONY : src/Scenes/TestScene.cpp.o

src/Scenes/TestScene.i: src/Scenes/TestScene.cpp.i

.PHONY : src/Scenes/TestScene.i

# target to preprocess a source file
src/Scenes/TestScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/TestScene.cpp.i
.PHONY : src/Scenes/TestScene.cpp.i

src/Scenes/TestScene.s: src/Scenes/TestScene.cpp.s

.PHONY : src/Scenes/TestScene.s

# target to generate assembly for a file
src/Scenes/TestScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/Scenes/TestScene.cpp.s
.PHONY : src/Scenes/TestScene.cpp.s

src/collisions.o: src/collisions.cpp.o

.PHONY : src/collisions.o

# target to build an object file
src/collisions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/collisions.cpp.o
.PHONY : src/collisions.cpp.o

src/collisions.i: src/collisions.cpp.i

.PHONY : src/collisions.i

# target to preprocess a source file
src/collisions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/collisions.cpp.i
.PHONY : src/collisions.cpp.i

src/collisions.s: src/collisions.cpp.s

.PHONY : src/collisions.s

# target to generate assembly for a file
src/collisions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/collisions.cpp.s
.PHONY : src/collisions.cpp.s

src/controlls.o: src/controlls.cpp.o

.PHONY : src/controlls.o

# target to build an object file
src/controlls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/controlls.cpp.o
.PHONY : src/controlls.cpp.o

src/controlls.i: src/controlls.cpp.i

.PHONY : src/controlls.i

# target to preprocess a source file
src/controlls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/controlls.cpp.i
.PHONY : src/controlls.cpp.i

src/controlls.s: src/controlls.cpp.s

.PHONY : src/controlls.s

# target to generate assembly for a file
src/controlls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/controlls.cpp.s
.PHONY : src/controlls.cpp.s

src/framework.o: src/framework.cpp.o

.PHONY : src/framework.o

# target to build an object file
src/framework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/framework.cpp.o
.PHONY : src/framework.cpp.o

src/framework.i: src/framework.cpp.i

.PHONY : src/framework.i

# target to preprocess a source file
src/framework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/framework.cpp.i
.PHONY : src/framework.cpp.i

src/framework.s: src/framework.cpp.s

.PHONY : src/framework.s

# target to generate assembly for a file
src/framework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/framework.cpp.s
.PHONY : src/framework.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/image.o: src/image.cpp.o

.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i

.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s

.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map.o: src/map.cpp.o

.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/moving.o: src/moving.cpp.o

.PHONY : src/moving.o

# target to build an object file
src/moving.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/moving.cpp.o
.PHONY : src/moving.cpp.o

src/moving.i: src/moving.cpp.i

.PHONY : src/moving.i

# target to preprocess a source file
src/moving.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/moving.cpp.i
.PHONY : src/moving.cpp.i

src/moving.s: src/moving.cpp.s

.PHONY : src/moving.s

# target to generate assembly for a file
src/moving.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/moving.cpp.s
.PHONY : src/moving.cpp.s

src/scene.o: src/scene.cpp.o

.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i

.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s

.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

src/scenesprite.o: src/scenesprite.cpp.o

.PHONY : src/scenesprite.o

# target to build an object file
src/scenesprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scenesprite.cpp.o
.PHONY : src/scenesprite.cpp.o

src/scenesprite.i: src/scenesprite.cpp.i

.PHONY : src/scenesprite.i

# target to preprocess a source file
src/scenesprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scenesprite.cpp.i
.PHONY : src/scenesprite.cpp.i

src/scenesprite.s: src/scenesprite.cpp.s

.PHONY : src/scenesprite.s

# target to generate assembly for a file
src/scenesprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/scenesprite.cpp.s
.PHONY : src/scenesprite.cpp.s

src/sprite.o: src/sprite.cpp.o

.PHONY : src/sprite.o

# target to build an object file
src/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/sprite.cpp.o
.PHONY : src/sprite.cpp.o

src/sprite.i: src/sprite.cpp.i

.PHONY : src/sprite.i

# target to preprocess a source file
src/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/sprite.cpp.i
.PHONY : src/sprite.cpp.i

src/sprite.s: src/sprite.cpp.s

.PHONY : src/sprite.s

# target to generate assembly for a file
src/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/sprite.cpp.s
.PHONY : src/sprite.cpp.s

src/synth.o: src/synth.cpp.o

.PHONY : src/synth.o

# target to build an object file
src/synth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/synth.cpp.o
.PHONY : src/synth.cpp.o

src/synth.i: src/synth.cpp.i

.PHONY : src/synth.i

# target to preprocess a source file
src/synth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/synth.cpp.i
.PHONY : src/synth.cpp.i

src/synth.s: src/synth.cpp.s

.PHONY : src/synth.s

# target to generate assembly for a file
src/synth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/synth.cpp.s
.PHONY : src/synth.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TJE.dir/build.make CMakeFiles/TJE.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... TJE"
	@echo "... tweeny-dummy"
	@echo "... src/Managers/ImageManager.o"
	@echo "... src/Managers/ImageManager.i"
	@echo "... src/Managers/ImageManager.s"
	@echo "... src/Scenes/MenuScene.o"
	@echo "... src/Scenes/MenuScene.i"
	@echo "... src/Scenes/MenuScene.s"
	@echo "... src/Scenes/TestScene.o"
	@echo "... src/Scenes/TestScene.i"
	@echo "... src/Scenes/TestScene.s"
	@echo "... src/collisions.o"
	@echo "... src/collisions.i"
	@echo "... src/collisions.s"
	@echo "... src/controlls.o"
	@echo "... src/controlls.i"
	@echo "... src/controlls.s"
	@echo "... src/framework.o"
	@echo "... src/framework.i"
	@echo "... src/framework.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/moving.o"
	@echo "... src/moving.i"
	@echo "... src/moving.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/scenesprite.o"
	@echo "... src/scenesprite.i"
	@echo "... src/scenesprite.s"
	@echo "... src/sprite.o"
	@echo "... src/sprite.i"
	@echo "... src/sprite.s"
	@echo "... src/synth.o"
	@echo "... src/synth.i"
	@echo "... src/synth.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

